sudo: required
env:
  - PATH=$PATH:${HOME}/google-cloud-sdk/bin
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
language: java
services:
  - docker

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - apt-get -qq update
install:
  - apt-get install -y kubectl
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then
      rm -rf $HOME/google-cloud-sdk;
      curl https://sdk.cloud.google.com | bash;
    fi

before_script:
  - openssl aes-256-cbc -K $encrypted_75ff630235d1_key -iv $encrypted_75ff630235d1_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
  - tar -xzf credentials.tar.gz
  - gcloud config set project kahd-001
  - gcloud auth activate-service-account --key-file client-secret.json
script:
  - gcloud --version
  - make deploy-api
