sudo: false
language: java
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
env:
- PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
- openssl aes-256-cbc -K $encrypted_75ff630235d1_key -iv $encrypted_75ff630235d1_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
- tar -xzf credentials.tar.gz
- ls ${HOME}/google-cloud-sdk || true
- ls ${HOME}/google-cloud-sdk/bin || true
- if [ ! -d ${HOME}/google-cloud-sdk ]; then
     curl https://sdk.cloud.google.com | bash;
  fi
- gcloud auth activate-service-account --key-file client-secret.json
install:
- gcloud config set project kahd-001
script:
- echo test
