sudo: required
env:
  global:
    - PATH=$PATH:${HOME}/google-cloud-sdk/bin
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
language: java
services:
  - docker

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/google-cloud-sdk/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
    - openssl aes-256-cbc -K $encrypted_75ff630235d1_key -iv $encrypted_75ff630235d1_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
    - tar -xzf credentials.tar.gz
install:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then
      rm -rf $HOME/google-cloud-sdk;
      curl https://sdk.cloud.google.com | bash;
    fi
  # Install Kubectl - TODO: See if we can cache this.
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/

before_script:
  - gcloud config set project kahd-001
  - gcloud config set compute/zone europe-west2-a
  - gcloud auth activate-service-account --key-file client-secret.json
  - export API_VERSION=`cat kahd-api/VERSION`-$TRAVIS_BUILD_NUMBER
  - export API_DOCKER_IMG=eu.gcr.io/kahd-001/kahd-api:$API_VERSION

script:
  - make build-api
  - docker tag kahd-api $API_DOCKER_IMG
  - gcloud docker -- push $API_DOCKER_IMG

  - ./kahd-api/setup-cluster.sh dev
  - kubectl run kahd-api --image=$API_DOCKER_IMG --port 8080 || true
  - kubectl expose deployment kahd-api --type=LoadBalancer --port 80 --target-port 8080 || true
  - kubectl set image deployment/kahd-api kahd-api=$API_DOCKER_IMG
  - invalid command
  - ./kahd-api/setup-cluster.sh prod
  - kubectl run kahd-api --image=$API_DOCKER_IMG --port 8080 || true
  - kubectl expose deployment kahd-api --type=LoadBalancer --port 80 --target-port 8080 || true
  - kubectl set image deployment/kahd-api kahd-api=$API_DOCKER_IMG
