services:
  database:
    image: postgres:17-alpine
    container_name: kahd-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432
    networks:
      - test-network
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s

  integration-tests:
    build:
      context: .
      target: builder
    environment:
      - TEST_DB_CONNECTION_STRING=postgres://postgres:postgres@database:5432/postgres?sslmode=disable
    networks:
      - test-network
    depends_on:
      database:
        condition: service_healthy
    command: go test ./... --tags=integration

networks:
  test-network:
    driver: bridge
