name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.23.1
    - name: Run unit tests
      run: make test-unit
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: make build
  
  e2e-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run end-to-end tests
      run: make test-e2e
