name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23.1
    - name: Run unit tests
      run: make test-unit

  e2e-test:
    runs-on: ubuntu-latest
    needs: unit-test

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Compose
      run: sudo apt-get update && sudo apt-get install -y docker-compose
    - name: Run end-to-end tests
      run: make test-e2e