name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23.1
    - name: Run unit tests
      run: make test-unit

  build:
    runs-on: ubuntu-latest
    needs: unit-test

    steps:
    - uses: actions/checkout@v4
    - name: Set commit hash as build-tag
      run: echo "BUILD_TAG=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
    - name: Build the server image
      run: make TAG=$BUILD_TAG build-server
    - name: Save the server image
      run: docker save -o /tmp/kahd-api-server.tar kahd-api-server            
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: server-image
        path: /tmp/kahd-api-server.tar

  e2e-test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: server-image
        path: /tmp
    - name: Load the server image
      run: docker load --input /tmp/kahd-api-server.tar

    - name: Set up Docker Compose
      run: sudo apt-get update && sudo apt-get install -y docker-compose
    - name: Run end-to-end tests
      run: make test-e2e
