name: Deploy

on:
  workflow_run:
    workflows: ["Build and test"]
    branches: ["main"]
    types:
      - completed

env:
  PROJECT_ID: "kahd-001"
  PROJECT_NUMBER: "561203979895"
  SERVICE_ACCOUNT: "githubactions"
  IDENTITY_POOL: "kahd-ci-identity-pool"
  REGION: "europe-central2"
  SERVER_IMAGE: "kahd-api-server"
  IMAGE_REGISTRY: "docker-images"


jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: 'Google Cloud Authentication'
      id: google-auth
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        project_id: ${{ env.PROJECT_ID }}
        service_account: ${{ env.SERVICE_ACCOUNT }}@${{ env.PROJECT_ID }}.iam.gserviceaccount.com
        workload_identity_provider: projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ env.IDENTITY_POOL }}/providers/github-actions-provider

    - name: Docker Authentication
      id: docker-auth
      uses: 'docker/login-action@v1'
      with:
        username: 'oauth2accesstoken'
        password: '${{ steps.google-auth.outputs.access_token }}'
        registry: '${{ env.REGION }}-docker.pkg.dev'

    - name: Get build-tag
      id: get-tag
      run: echo ::set-output name=short_ref::$(git rev-parse --short "$GITHUB_SHA")

    - name: Push server image
      uses: docker/build-push-action@v6
      with:
        target: api-server
        push: true
        tags: |
            ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.IMAGE_REGISTRY }}/${{ env.SERVER_IMAGE }}:latest
            ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.IMAGE_REGISTRY }}/${{ env.SERVER_IMAGE }}:${{ steps.get-tag.outputs.short_ref }}

    - name: Update instance
      run: |
        gcloud compute instances update-container kahd-api-server \
          --container-image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.IMAGE_REGISTRY }}/${{ env.SERVER_IMAGE }}:${{ steps.get-tag.outputs.short_ref }} \
          --zone=${{ env.REGION }}-a