name: Smoke test

on:
  workflow_run:
    workflows: ["Deploy"]
    types:
      - completed
  schedule:
    - cron: "0 1 * * 1"

jobs:
  smoke-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build end-to-end tests
      run: make build-e2e-tests
    - name: Run end-to-end tests
      run: docker run --rm -e HOST=api.kahd.milesjpool.com kahd-e2e-tests